FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.4@sha256:32c0e6e5c4f6707717051091b4d0b077464a679eaab563e11474efc5328e2aa5 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-git-clone"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-git-clone"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-git-clone"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-git-clone"

RUN apk --update add --no-cache git openssh curl git-lfs && \
    apk upgrade --no-cache zlib libcrypto3 && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/wp-git-clone /bin/wp-git-clone
ENTRYPOINT [ "/bin/wp-git-clone" ]
