FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.23.3@sha256:d56c3e08fe5b27729ee3834854ae8f7015af48fd651cd25d1e3bcf3c19830174 AS build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.20@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-git-clone"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-git-clone"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-git-clone"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-git-clone"

RUN apk --update add --no-cache git openssh curl git-lfs && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/wp-git-clone /bin/wp-git-clone
ENTRYPOINT [ "/bin/wp-git-clone" ]
