---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: lint
    image: docker.io/library/golang:1.25.2
    commands:
      - make deps lint

  - name: test
    image: docker.io/library/golang:1.25.2
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends git git-lfs
      - make deps test
